### ISSUE TITLE
Compact generator with waterlogged stairs

### ISSUE THREAD

**Issue by FesterHead** [BentoBoxWorld/MagicCobblestoneGenerator#47] opened 2020-05-30 20:25 UTC
A compact generator built following the following video does not register as a cobblestone generator.
https://www.youtube.com/watch?v=N-MYtwNPJcc

I've modified it a bit to wrap the lava in trapdoors to contain it within one block.
When mining the cobblestone, this does not register as being a cobblestone generator.
The same happens if I remove the bottom trapdoor and let the lava flow.
<img width="642" alt="01-does-not-register-as-generator" src="https://user-images.githubusercontent.com/1421244/83338303-d73dd280-a25e-11ea-8156-b77185debb3f.png">

However, when I break the sign on the step portion of the stair block and let the water flow down then breaking blocks is treated as a cobblestone generator.
<img width="741" alt="02-does-register-as-generator" src="https://user-images.githubusercontent.com/1421244/83338347-474c5880-a25f-11ea-9e65-fc8e49627e0d.png">

Not a big deal as I've transformed the water column into a fountain that feeds a pond.  (no picture attached) 

Probably related to the fence feature request? #12 

/bentobox version
<img width="567" alt="plugins" src="https://user-images.githubusercontent.com/1421244/83338554-2c7ae380-a261-11ea-81a8-189fc0745a5e.png">

**Comment by BONNe** [comment] 2020-05-30 20:43
Does this works in vanilla game?

**Comment by FesterHead** [comment] 2020-05-30 21:00
Yes on git-Paper-327 (MC: 1.15.2) and plain 'ole 1.15.2

**Comment by tastybento** [comment] 2020-05-31 01:03
Should be fixed now. Please try the latest snapshot and see if that works for you.

**Comment by FesterHead** [comment] 2020-05-31 16:42
The generator described in the first picture is working with magiccobblestonegenerator-1.9.1-SNAPSHOT.jar
Thanks for the update!

**Comment by tastybento** [comment] 2020-05-31 23:45
FYI, #48 was caused by this fix. See the latest build that fixes that one.

**Comment by FesterHead** [comment] 2020-06-01 00:08
Grabbed the Build #105 of magiccobblestonegenerator-1.9.1-SNAPSHOT.jar and will check it out.

**Comment by FesterHead** [comment] 2020-06-01 00:37
The waterlogged stair still works as a cobblestone generator - with side-effects.
1. The new block appears much quicker than before.  There used to be a delay of a second or so before the new block would appear.  Wow.  I can cobblejack a ton now!
2.  Broken blocks are not registered by the McMMO plugin anymore for gaining mining points.

Build 105 video.  New blocks appear fast and McMMO not registered.  The new block is still registered as coming from the magic cobblestone generator.  Otherwise cobblestone would appear.
[build-105](https://streamable.com/8t4w8m)

Build 104 video.  New blocks take a second to appear and McMMO skill increases.  The new block is still registered as coming from the magic cobblestone generator.  Otherwise cobblestone would appear.
[build-104](https://streamable.com/0o9h7c)

Before build 104, the blocks appeared fast, did not trigger McMMO nor the generator level.

**Comment by tastybento** [comment] 2020-06-01 19:32
So, 105 is faster, but McMMO doesn't register the new block? So, just to clarify you'd like McMMO to be able to register the new block, right?

**Comment by FesterHead** [comment] 2020-06-02 04:12
Yes to both.
Having the magic cobblestone generator and mcmmo work together is ideal - like build 104.

I did not mention previously; both build 104 and 105 give payouts for the Jobs Reborn plugin.

**Comment by tastybento** [comment] 2020-06-02 14:36
I can't commit to making 105 register with McMMO. I had a look through their code and I'm not sure what specifically makes a block "ok" or not. If someone else reading this knows, that'd be useful. I'll have another look later.

**Comment by FesterHead** [comment] 2020-06-03 05:03
I don't know, sorry, but I can live without McMMO or build a more regular cobblestone generator.

**Closed** 2020-06-06 17:04 UTC
Labels: bug, done
