### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mich3l3k** [BentoBoxWorld/MagicCobblestoneGenerator#92] opened 2021-03-05 22:33 UTC
#### Describe the bug
When cave's owner is offline, members can't use /c generator
Player gets error

#### Steps to reproduce the behavior
Create cave
Invite someone to cave
Leave from game
And now member must try use /c generator

#### Expected behavior
Well, this command should opens GUI with generators

#### Screenshots and videos (Optional)
![an_ub](https://user-images.githubusercontent.com/47540709/110180873-e31c7d80-7e0a-11eb-860d-726d08a28a74.png)

##### Output of `/bbox version` (Mandatory)

```
[Fri, 5. Mar 2021 23:32:24 CET INFO] Serwer działa na PAPER 1.16.4.
[Fri, 5. Mar 2021 23:32:24 CET INFO] Wersja BentoBoxa: 1.15.5
[Fri, 5. Mar 2021 23:32:24 CET INFO] Baza danych: MYSQL
[Fri, 5. Mar 2021 23:32:24 CET INFO] Wczytane światy gry:
[Fri, 5. Mar 2021 23:32:24 CET INFO] caveblock-world (CaveBlock): Świat jaskiń, Nether, End
[Fri, 5. Mar 2021 23:32:24 CET INFO] Wczytane dodatki:
[Fri, 5. Mar 2021 23:32:24 CET INFO] Bank 1.3.0 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Biomes 1.14.0 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] CaveBlock 1.14.2 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Challenges 0.8.3 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] ControlPanel 1.7.0 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] DimensionalTrees 1.6.0 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] ExtraMobs 1.11.0.3 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Level 2.6.0 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Limits 1.15.5 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] MagicCobblestoneGenerator 2.2.1 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] TwerkingForTrees 1.4.1 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Upgrades 0.2.0-SNAPSHOT-b80 (ENABLED)
[Fri, 5. Mar 2021 23:32:24 CET INFO] Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
[Fri, 5. Mar 2021 23:32:50 CET INFO] Plugins (38): AdvancedBan*, AdvancedHelp, AuctionHouse, BentoBox, BungeeTabListPlus, ChatManager, ChatReaction, ChestShop, CoreProtect, DiscordSRV, DynamicShop, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, GoldenCrates, GSit, HolographicDisplays, HolographicPlaceholders, LuckPerms, MysqlPlayerDataBridge, NexEngine, NightVision*, OnlineTime, OpenInv, PacketLimiter, PlaceholderAPI, ProtocolLib, SilkSpawners, SkinsRestorer, spark, TradeSystem, UltimateAutoRestart, Vault, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags
```
 
### Additional context (Optional)
nope

**Comment by BONNe** [comment] 2021-03-06 16:42
Duplicate of #87

**Closed by BONNe** 2021-03-06 16:42 UTC
Labels: Status: Done, Status: Duplicate
